### ISSUE TITLE
Team path separator Issue with CxGo

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/checkmarx-spring-boot-java-sdk#14]
If the team ends with a \ when using cxgo, the processing will fail:
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [The business application with the same name already exists]

# This works
```
  team: \businessUnit
```
# This does not
```
  team: \businessUnit\
```

**Comment by cx-aviv-sevillia** [comment]
Fixed by cxflow pull request: #505
https://github.com/checkmarx-ltd/cx-flow/pull/505
