### ISSUE TITLE
Scan launched before project branching completes

### ISSUE THREAD

**Issue by cx-james-bostock** [checkmarx-ltd/checkmarx-spring-boot-java-sdk#278]
In the case that the SDK creates a branched project, it is possible that it will launch a scan before the branching process completes. In recent versions of SAST, this will lead to the scan being canceled:

```
2022-11-29 09:41:47,555 [47] INFO - ScanRequest with id 1685335 was canceled. Branching process is not yet completed.
```

In older versions of SAST, I am told the scan would simply fail.

The SDK should be enhanced to address this issue. Newer versions of SAST provide an API endpoint for checking the branching status (GET /projects/branch/{id}) - if available, this endpoint should be used to prevent the scan being launched before branching has completed. For versions of SAST that do not have this endpoint, a configurable pause could be added after the branch request has been made.

**Comment by vlsecurity** [comment]
@james-bostock-cx we have the same issue with **cx-flow** in our **gitlab-ci** for scan on new MR with branched project creation, because cx-flow uses java SDK. We created support ticket, and would appreciate fast fix for this issue.

**Comment by cx-james-bostock** [comment]
Hi @vlsecurity,
I submitted a pull request to address this issue in December: https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/279 (which was subsequently merged). As such, I am going to close this issue. There isn't yet an official CxFlow release that contains this fix. CxFlow version 1.6.39 will include the fix. I am not sure of the planned release date but there is a pre-release available that includes the fix.
